---
title: "Overview"
output: html_document
---

<style type="text/css">
.title {
  display: none;
}

img {
  margin: 40px;
}

</style>

<div class="row" style="padding-top: 30px;">
<div class="col-sm-6">



```{r Setup, warning=FALSE, include=FALSE, results='hide'}
library(knitr)

data_location <- "/Users/tbrambor/Dropbox (Pflegedienst Brambor)/Reform_Capacity_TB/Research_Assistance/Leaders/"

library(readxl)
library(plyr)
library(readstata13)
library(reshape2)
library(dplyr)
library(ggthemes)
library(plotly)
library(countrycode)
library(readr)
library(dplyrExtras)
library(DescTools)  # for lambda
library(DT)

```

```{r, message=FALSE, warning=FALSE, echo=FALSE}
hogcy <- read_excel(paste(data_location,"/v1.4/HoG_dataset_country_year_v1.4.xls",sep=""))

hogcy$hogideo <- factor(hogcy$hogideo, levels = c("L","C","R","O"))
hogcy$hogideo <- revalue(hogcy$hogideo, c(L = "Left", C = "Center", R = "Right", O = "Other"))
detach("package:plyr", unload=TRUE)

## Add BMR data
library(readstata13)
bmr <- read.dta13(paste(data_location,"/codebook/boix_temporary.dta",sep=""))

data <- dplyr::left_join(hogcy, bmr, by = c(year="year", ccodecow = "ccodecow"))
```


## Head of Government Ideology by Regime Types

Using the most current data on the heads of governments, I re-created our original graphs. The step functions are more true to our annual data structure, I believe.

```{r, message=FALSE, warning=FALSE, echo=FALSE, dpi=300}
theme_new <- function(base_size = 12, base_family = "Helvetica"){
  theme_few(base_size = base_size, base_family = base_family) %+replace%
    theme(
      #line = element_line(colour="black"),
      #text = element_text(colour="black"),
      #axis.text = element_text(colour="black", size=8),
      #strip.text = element_text(size=12),
      #legend.key=element_rect(colour=NA, fill =NA),
      panel.grid = element_blank(),   
      panel.border = element_blank(),
      plot.title = element_text(size=base_size+4, vjust=3, hjust = 0.5)
      )
}

# Colors for the ideology categories (L,C,R,O)
color3 <- c("#cf6363","#ffe866","#91b6d4")
color4 <- c("#cf6363","#ffe866","#91b6d4","#D3D3D3")

#color4 <- c("#ef8a62","#fee090","#67a9cf","#D3D3D3")

## Graph Ideology for all Regimes
data %>% 
  dplyr::filter(hogideo!="Other") %>% 
  group_by(year, hogideo) %>% 
  summarise(count=n()) %>% 
  mutate(perc=count/sum(count)) %>%
ggplot(aes(x=year, y=perc, fill=hogideo)) + 
  geom_bar(position = "stack", stat = "identity", size = 0, width=1.1) +
  scale_fill_manual(values=color3) + 
  labs(x = "Year", y = "Proportion of Countries", title = "All Regimes", fill = "Ideology") + 
  scale_x_continuous(breaks = seq(1875,2000,25), expand = c(0, 0)) + scale_y_continuous(expand = c(0, 0)) +
  theme_new() -> g
g

## Graph Ideology for all Democracies
data %>% 
  dplyr::filter(boix_democracy == 1) %>% 
  dplyr::filter(hogideo!="Other") %>% 
  group_by(year, hogideo) %>% 
  summarise(count=n()) %>% 
  mutate(perc=count/sum(count)) %>%
ggplot(aes(x=year, y=perc, fill=hogideo)) + 
  geom_bar(position = "stack", stat = "identity", size = 0, width=1.1) +
  scale_fill_manual(values=color3) + 
  labs(x = "Year", y = "Proportion of Countries", title = "Democracies", fill = "Ideology") + 
  scale_x_continuous(breaks = seq(1875,2000,25), expand = c(0, 0)) + scale_y_continuous(expand = c(0, 0)) +
  theme_new() + theme(plot.title = element_text(vjust=30)) -> g
g

## Graph Ideology for all Dictatorships
data %>% 
  dplyr::filter(boix_democracy == 0) %>% 
  dplyr::filter(hogideo!="Other") %>% 
  group_by(year, hogideo) %>% 
  summarise(count=n()) %>% 
  mutate(perc=count/sum(count)) %>%
ggplot(aes(x=year, y=perc, fill=hogideo)) + 
  geom_bar(position = "stack", stat = "identity", size = 0, width=1.1) +
  # scale_fill_grey() +
  scale_fill_manual(values=color3) + 
  labs(x = "Year", y = "Proportion of Countries", title = "Dictatorships", fill = "Ideology") + 
  scale_x_continuous(breaks = seq(1875,2000,25), expand = c(0, 0)) + scale_y_continuous(expand = c(0, 0)) +
  theme_bw() -> g
g
```